/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 madara.glb 
Author: Romélus 3D (https://sketchfab.com/Romelus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/madara-uchiha-uchiwa-non-edo-tensei-6ae9d16b88b84c769c83059b22a17159
Title: Madara Uchiha (Uchiwa) - Non - edo tensei
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Madara(props) {
  const { nodes, materials } = useGLTF('/madara.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.192}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Body_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Body_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group position={[-30.345, -16.597, 2.192]} rotation={[-0.925, -0.384, -2.848]} scale={4.473}>
            <group position={[-14.781, -2.087, 3.122]} rotation={[0.049, -0.525, 2.869]} scale={[20.084, 20.411, 21.42]}>
              <mesh geometry={nodes.Beans_Armor_0.geometry} material={materials.Armor} />
              <mesh geometry={nodes.Beans_Outline_0.geometry} material={materials.Outline} />
            </group>
            <mesh geometry={nodes.Armor_Armor_0.geometry} material={materials.Armor} />
            <mesh geometry={nodes.Armor_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group position={[11.923, 43.236, -2.273]} rotation={[-3.14, 0.001, 0.307]} scale={3.384}>
            <group position={[-0.44, -3.564, -1.956]} rotation={[1.569, -0.307, 0]} scale={2.432}>
              <mesh geometry={nodes.Hairs_HairAndFace_0.geometry} material={materials.HairAndFace} />
              <mesh geometry={nodes.Hairs_Outline_0.geometry} material={materials.Outline} />
            </group>
            <mesh geometry={nodes.Head_HairAndFace_0.geometry} material={materials.HairAndFace} />
            <mesh geometry={nodes.Head_Outline_0.geometry} material={materials.Outline} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/madara.glb');
export default Madara;
