/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 shinto.glb 
Author: Deerex 🦖 (https://sketchfab.com/darrencontreras)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-shinto-shrine-53623498e0f941699a1c83542b5da223
Title: Japanese Shinto Shrine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shinto(props) {
  const { nodes, materials } = useGLTF('/shinto.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -3.086]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.SM_Shinto_Shrine_M_Trim_01_0.geometry} material={materials.M_Trim_01} />
          <mesh geometry={nodes.SM_Shinto_Shrine_M_Concrete_0.geometry} material={materials.M_Concrete} />
          <mesh geometry={nodes.SM_Shinto_Shrine_M_Trim_02_0.geometry} material={materials.M_Trim_02} />
          <mesh geometry={nodes.SM_Shinto_Shrine_M_RoofTile_0.geometry} material={materials.M_RoofTile} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shinto.glb');
export default Shinto
